import styles from './Footer.module.scss';

const Footer: React.FC = () => (
  <footer className={styles.footer}>
    <a
      href="https://github.com/gonzzj"
      target="_blank"
      rel="noopener noreferrer"
    >
      Created by Gonzalo Jusid
    </a>
  </footer>
);

Footer.defaultProps = { 
  title: "My Favorites Cities",
  metaDescription: "Generated by create next app"
};

export default Footer;