import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import CitiesSelect from '../components/CitiesSelect'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Favorites Cities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Select your favorite cities
        </h1>

        <CitiesSelect />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/gonzzj"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Gonzalo Jusid
        </a>
      </footer>
    </div>
  )
}

export default Home
